### ISSUE TITLE
Can not query my server no matter what I try ...

### ISSUE THREAD

**Issue by bloggy** [xPaw/PHP-Minecraft-Query#100]
Hi there,
I can not get the query script working at all. 

My minecraft server ip: 176.31.104.74
My webserver ip: 188.40.57.130

This is my php configuration:
http://pastebin.com/bcfSWWcv

This is my server.properties (server is running spigot 1.8.3):
http://pastebin.com/0Q04beBZ

This is the script page:
http://lyriaserver.de/test/view.php

Error:

Failed to receive status.
#0 /var/www/webs/lyria/test/view.php(25): xPaw\MinecraftQuery->Connect('176.31.104.74', 25565, 1)
#1 {main}

How can I fix this? What's the problem?

**Comment by xPaw** [comment]
Try setting `query.port` to a port that is different to `server-port`

**Comment by Spirit55555** [comment]
I can query your server just fine, so the problem must be with your webhost/webserver.

**Comment by bloggy** [comment]
I tried a different port, yet.

I have a feeling that it could have something to do with my webserver. But what could be the issue? Can you send me your php config so I can compare?

**Comment by bloggy** [comment]
I think the script worked in the past but only when there were a maximum of 17 players on the server.
I searched this in google and found this:
http://www.spigotmc.org/threads/query-only-returns-12-online-playernames.23646/
But no solution in the thread there.

Do you have any idea why the query script would not show results when there are more than 17 players on the server?

**Comment by Spirit55555** [comment]
ServerPing only returns 12 players, pr. default, Query returns all.

Is `fsockopen()` enabled on your webserver?

**Comment by bloggy** [comment]
Yes fsockopen() works, here is a test script:
http://www.lyriaserver.de/test/test.php

**Comment by Spirit55555** [comment]
Then my best guess would be an issue with a firewall.

**Comment by bloggy** [comment]
I don't have a firewall :-( The webserver is running on my own dedicated server and there is no firewall at all

**Comment by bloggy** [comment]
Did not want to close this. :-O
Any more suggestions what I could try?

**Comment by bloggy** [comment]
I tried to upload the script on a different webhost (sockets enabled) but there is another error:

Notice: fwrite(): send of 7 bytes failed with errno=1 Operation not permitted in /home/u303538066/public_html/src/MinecraftQuery.php on line 174

Failed to write on socket.
#0 /home/u303538066/public_html/view.php(25): xPaw\MinecraftQuery->Connect('176.31.104.74', 25565, 1)
#1 {main}

What does it mean?

URL: http://lyriaserver.esy.es/view.php

**Comment by bloggy** [comment]
Today the script worked for a short time. But when there were more than 10 players online it stopped working.

**Comment by xPaw** [comment]
I tried your server with both query and ping libs, and get the server information just fine. Are you sure your server configuration/firewall are not dropping the connections?

**Comment by bloggy** [comment]
I don't know what part of a server configuration could do something like this, I mean, if something would block it it would not work at all. But it works as far as there are 10 players on the server.

**Comment by xPaw** [comment]
Not a clue, really. Try it on a different server or locally.

Here's a screenshot:
![2015-04-29-1603pobtv](https://cloud.githubusercontent.com/assets/613331/7392021/9b07cb2a-ee8d-11e4-961a-74d1982328ed.png)

**Comment by xPaw** [comment]
Also, your website hoster blocks UDP: http://www.hostinger.de/wissensdatenbank/787.html

**Comment by bloggy** [comment]
Thank you, but can you pls remove the screenshot showing the plugins of the server?
I will look into this further.
