### ISSUE TITLE
View severping

### ISSUE THREAD

**Issue by epicTCK** [xPaw/PHP-Minecraft-Query#103]
When I am on, the chart looks like 
![screen shot 2015-06-24 at 7 35 52 pm](https://cloud.githubusercontent.com/assets/10236989/8343932/eeb11550-1aa8-11e5-8e19-7dfd4e434d17.png)

**Comment by South-Paw** [comment]
That's working as intended then...?

You'll need to write your own code from there and parse the results.

**Comment by epicTCK** [comment]
Sorry I'm 13 and just getting into the world of programming. I know basic html and a decent amount of JavaScript, and currently learning c#, but I don't know any php. It does work as intended, I'm no sure how to work with arrays in php (assuming the array shown is in php).
I assume I could get my name by doing something like 

nameOfArray[name]

but I don't know where to write that, if that would work and how to get rid of the show code.

I personaly don't mind seeing all the extra stuff but it might be dounting for my server users to decipher. If you could show me how I could get it to simply show the name, id, etc that would be great.

**Comment by HaibaneNero** [comment]
@epicTCK Github Issues are only for thing related to its sourcecode, not language details in general nor a support forum. Use StackOverflow instead.

And read the PHP documentation (http://php.net/manual/en/language.types.array.php) or similar.
@epicTCK Github Issues are only for thing related to its sourcecode, not language details in general nor a support forum. Use StackOverflow instead.

And read the PHP documentation (http://php.net/manual/en/language.types.array.php) or similar.
