### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by xPaw** [xPaw/PHP-Minecraft-Query#104]
Right now the license is CC BY-NC-SA 3.0, which is not really suited for code projects, and is recommended against. Using MIT would be more suited, and be more permissive.

However I need to get a confirmation from everyone that contributed to this repository in the past:
- [x] @Lekensteyn (6 commits)
- [x] @beefsack (6 commits)
- [x] @mrsmn (2 commits)
- [x] @perry-mitchell (2 commits)
- [x] @Erikvv
- [x] @South-Paw
- [x] @zh32
- [x] @Rodolffo
- [x] @navarr
- [x] @aaronklaassen
- [x] @XabstraktionX

**Comment by beefsack** [comment]
Confirmed :+1:

**Comment by Erikvv** [comment]
Whatevs :+1:

**Comment by mrsmn** [comment]
Works for me :+1:

**Comment by navarr** [comment]
This is always fun.  You've got my approval :thumbsup:

**Comment by XabstraktionX** [comment]
Approved

**Comment by aaronklaassen** [comment]
Heh yep go for it.

**Comment by Rodolffo** [comment]
Of course I approve, I've always favorited MIT myself.

**Comment by perry-mitchell** [comment]
Yes, sounds great.

**Comment by Lekensteyn** [comment]
ACK for MIT.

**Comment by zh32** [comment]
:+1:

**Comment by South-Paw** [comment]
:+1:
