### ISSUE TITLE
every server "connection refused"

### ISSUE THREAD

**Issue by lghenk** [xPaw/PHP-Minecraft-Query#108]
Hello,

I have a server database from 280+ servers but every server gets connection refused or times out
http://prntscr.com/87m0vl
(some servers get "php_network_getaddresses: getaddrinfo failed: Name or service not known") but i assume thats either the server doesn't exist anymore or SRV IP

Got any idea what it might be? i've been trying to figure this out over the last 2 days, its probably something simple i looked over, but so far i couldn't figure this out

**Comment by xPaw** [comment]
Your DNS is failing.

**Comment by lghenk** [comment]
That seems strange because i've tested it on 4 different servers With & without cloudflare,
and different hosts,

Also tried to restart the DNS & server no dice

**Comment by lghenk** [comment]
@xPaw 
That seems strange because i've tested it on 4 different servers With & without cloudflare,
and different hosts,

Also tried to restart the DNS & server no change

**Comment by HaibaneNero** [comment]
loghenk: This is most likely a error with your local setup. Issues handled here are related to the codebase itself, not the individual setups or servers.

Also, the 4th Server in your image is not valid, it has 2 port numbers (<host>:<port>:<port>).
