### ISSUE TITLE
Query of Server Running Bungee

### ISSUE THREAD

**Issue by stoi2m1** [xPaw/PHP-Minecraft-Query#109]
I have bungee and two minecraft servers running and I am unable to connect and query data, but I can ping and get some info back from the bungee server.

Do you have any info on how to configure running bungee, or do I connect to the minecraft servers?

**Comment by xPaw** [comment]
This is not an issue with the library.

**Comment by stoi2m1** [comment]
Ya shortly after I wrote this port I found the UDP portion of the port was not open. Thanks for confirming its likely something on my system.
