### ISSUE TITLE
Unable to use both query methods on the same object

### ISSUE THREAD

**Issue by z1haze** [xPaw/PHP-Minecraft-Query#110]
In my script, I create a new minecraft ping class, and try to normal query. it will return null if the server is < 1.7.

If i then try to run the QueryOldPre17() method, it always returns false. If i comment out the original call to $Query->Query(); it works.. It makes no sense?

**Comment by xPaw** [comment]
Probably because that server is sending multiple packets, and when you try to read for the second time it gets incorrect data and bails out (returns false).

**Comment by z1haze** [comment]
so how can I do this? I need to be able to query both old and new..

**Comment by z1haze** [comment]
I even tried closing the socket, and creating a new one, still same issue..

**Comment by xPaw** [comment]
It's UDP, I doubt it'll help. Try to add another `fread` before `fwrite` in `QueryOldPre17` to see if it reads any data.

**Comment by z1haze** [comment]
What do I pass as the second paramter for fread in this case? I dont have $remainder

**Comment by xPaw** [comment]
Try some number like 512.

**Comment by z1haze** [comment]
its empty

**Comment by z1haze** [comment]
try
        {
            $Query = new MinecraftPing($request['ip'], $request['server_port']);

        } catch (MinecraftPingException $e)
        {
            return redirect()->back()->withErrors(['We were unable to connect to the server'])->withInput();
        }

        $data = $Query->Query();
        //$Query->Close();

        $data=false;

        if (!$data)
        {
            $data = $Query->QueryOldPre17();
            $data['players']['online'] = $data['Players'];
            $data['players']['max'] = $data['MaxPlayers'];
            $data['version']['name'] = $data['Version'];
            $motd = trim(substr(preg_replace('/\xc2|\xa7.|\r|\n|\"./', '', $data['HostName']), 0, 31) . '...');
            dd($data);
        }
        
        $Query->close();

**Comment by xPaw** [comment]
I meant modify in `MinecraftPing.php`. Empty or not, does that make `QueryOldPre17` return real data?

**Comment by z1haze** [comment]
if I comment out the first $data = $Query->Query(); it will work... this is so goofy im not sure what to do

**Comment by z1haze** [comment]
thats what I meant, i modified your class method for the old query.. i dumped out the fread before fwrite and its an empty string

**Comment by xPaw** [comment]
Then the server is probably filtering/breaking something. That method is so old, it's probably time to remove it anyway. 1.7 was released two years ago.

**Comment by z1haze** [comment]
haha, yea i know man. But people still play modded servers that support 1.5.2

**Comment by z1haze** [comment]
enjin does it correctly though, wish i knew how. They are able to ping both old and new, and i dont THINK they require a server version before hand

**Comment by xPaw** [comment]
You'll have to figure it on your own then. I don't have interest in trying to fix something for servers that haven't been updated in 2 years.

**Comment by z1haze** [comment]
Its not that they havnt been updated. they are just on a older version of minecraft. What really determines 'updated' ? Most of those modded servers contain 1000x more stuff in the server than even 1.8.7 or w/e it is now.

Anyways, thanks for the quick replies.

**Comment by z1haze** [comment]
Actually just did some poking at your code.. its failing here:

fwrite($this->Socket, "\xFE\x01");
        $Data = fread($this->Socket, 512);
        $Len = StrLen($Data);

        if ($Len < 4 || $Data[0] !== "\xFF")
        {
            return false;
        }

this is the if statement where it breaks.. what is this?

**Comment by xPaw** [comment]
It means reply was either empty or invalid.

**Comment by z1haze** [comment]
you think it would be the same regardless of the order I run these 2 methods?

**Comment by xPaw** [comment]
You can try.

**Comment by z1haze** [comment]
Ok, well it seems to grab the new server data with the old method too.. what exactly is different? It seemed a lot slower, or maybe it just took a bit to connect to the server

**Comment by z1haze** [comment]
nevermind i see, all the new stuff like favicon, etc

**Comment by xPaw** [comment]
It's slow because server doesn't know what you're sending it and thus doesn't reply (you're sending <1.7 data to a >1.7 server).
