### ISSUE TITLE
Working with Bungee Query?

### ISSUE THREAD

**Issue by FrozenBeard** [xPaw/PHP-Minecraft-Query#112]
I have this working on my shared hosting Minecraft account, but when I put in my bungee details it breaks with:
    Notice: fwrite(): send of 7 bytes failed with errno=1 Operation not permitted in /home/user/public_html/website.com/online/src/MinecraftQuery.php on line 174
Failed to write on socket.

#0 /home/user/public_html/website.com/online/index.php(24): xPaw\MinecraftQuery->Connect('158.69.192.42', 25565, 1)
#1 {main}

It works from https://dinnerbone.com/minecraft/tools/status/

**Comment by xPaw** [comment]
Your web server is not allowing you to use sockets.

**Comment by FrozenBeard** [comment]
Does the bungee query use different code? 
Because its working perfectly fine with a non-bungee server.
