### ISSUE TITLE
Script doesn't return all players

### ISSUE THREAD

**Issue by ketamina96** [xPaw/PHP-Minecraft-Query#113]
Hi. I really appreciate your work. I read about "Script doesn't return  all players" in an old topic but i don't understand a thing. Why Minecraft doesn't allow you to take entire list of players, even if you know how many are online... I read about : modify script to extend limit, but i don't understand where , i through there's a static variable or something. Thank you and keep up the good work !:)

**Comment by SilentX88** [comment]
I can confirm bug.

For some reason cant see more than 400 players in players list, and our server in that time have 600 players

**Comment by SilentX88** [comment]
We found solution for this problem.
Just need to give more bytes for FRead.

We change in "MinecraftQuery.php" 
$Data = FRead( $this->Socket, 4096);
to 
$Data = FRead( $this->Socket, 16384);

**Comment by ketamina96** [comment]
Yes , works for me too :)
