### ISSUE TITLE
Can't get max or online players

### ISSUE THREAD

**Issue by MacXGaming** [xPaw/PHP-Minecraft-Query#114]
Hello.
I'm currently using this script for a little server list because it's the best out in the world, what I see :)

But somehow some servers return 0/0 but I can still see them online, get MOTD and all that, but no player info.
I'm using the MinecraftPing and not MinecraftQuery, because not all servers have query on.

Is it a problem with me, the server or what could it be?

**Comment by xPaw** [comment]
Not an issue since that's what the server returns.

**Comment by MacXGaming** [comment]
Alright. Thanks for letting me know :) Do you then know how that is happening and how servers can enable so it will send that data again?

**Comment by xPaw** [comment]
I do not.
