### ISSUE TITLE
Ping.php not dispaying online players

### ISSUE THREAD

**Issue by FrozenBeard** [xPaw/PHP-Minecraft-Query#115]
I recnelty switched to bungeecord (mc.piratemc.com) I can ping my url via dinnerbones tool and all players are displayed fine.
The script is up and working, all ports open as you can see http://piratemc.com/online/ping.php
But it is not showing the player list, this is the only thing I am interested in.
I have no idea why the other method of calling is not working: http://piratemc.com/online/

**Comment by xPaw** [comment]
Not an issue since that's what the server returns.

**Comment by FrozenBeard** [comment]
So the ping version does not collect the online players? Which leaves me with the Query method, which does not work at present as posted above.
I will be implementing this into a custom website I have been building and this is quite a priority to get working properly. 
I know that the server is setup correctly as players are being displayed when queried from https://dinnerbone.com/minecraft/tools/status/

**Comment by Spirit55555** [comment]
BungeeCord does not send a player list when you ping it. You have to use query for that.

**Comment by FrozenBeard** [comment]
yes, I came to that conclusion in my last reply, Question is then, why is the Query not working?
http://piratemc.com/online/

**Comment by Spirit55555** [comment]
Works fine on my status page: http://spirit55555.dk/mcstatus/mc.piratemc.com
So it's a problem with your web-server.

**Comment by FrozenBeard** [comment]
^ Thanks man. I just created a local clone and it worked too (bloody host!) Ill Pop them a ticket.
Thanks guys.
@Spirit55555 I love your layout for displaying MOTD, Good job!
