### ISSUE TITLE
PHP-Minecraft-Query Error

### ISSUE THREAD

**Issue by Berisko** [xPaw/PHP-Minecraft-Query#117]
Hello, recently I downloaded the xPaws "PHP-Minecraft-Query". Once I entered the information of my server I ran into this PHP error - "Notice: fwrite(): send of 7 bytes failed with errno=1 Operation not permitted in /home/mineqfvg/public_html/inc/inc/src/MinecraftQuery.php on line 174".
All information is correct. Is there a thing that needs to be enabled?

Berisko.

**Comment by xPaw** [comment]
Your server is blocking UDP.
