### ISSUE TITLE
Player nicknames with cyrillic characters displays wrong

### ISSUE THREAD

**Issue by NDruce** [xPaw/PHP-Minecraft-Query#121]
I logged on server as "Андрей", but in your library player list I shown as `=4@59`. Player "Рома" shown as `><0`

**Comment by Spirit55555** [comment]
"Андрей" is not a valid Minecraft name.

**Comment by NDruce** [comment]
But it work on my server, I changed all regex in server code and launcher to support these symbols, and want to show it properly even in query
