### ISSUE TITLE
How To Query Only For Players

### ISSUE THREAD

**Issue by ryancito02** [xPaw/PHP-Minecraft-Query#122]
No, I do not understand arrays.
However, I do know it is a table of values and infos.

I do know my share of PHP and HTML, and I am wondering,

Is there a way to concatanate some strings and player array into a string of information?

PSEUDOCODE :

Something like.. "The amount of players online currently is ' + $DATA(playercount) + '!"

Instead of ridiculing me and saying, "If you don't understand arrays, don't post issues.",
Can you just give me the code that spits out that information?

Many thanks.

**Comment by AMGitsKriss** [comment]
`count($Query->GetPlayers( ))`
Where $Query is your MinecraftQuery object.

**Comment by ryancito02** [comment]
I've transformed your code into 

  <?php echo count($Query->GetPlayers( )); ?>

However, it pops up with an undefined method error for GetPlayers. Perhaps GetPlayers is the wrong method to call on?


Fatal error: Uncaught Error: Call to undefined method xPaw\MinecraftPing::GetPlayers() in /home/test/website/view_serverping.php:127 Stack trace: #0 {main} thrown in /home/test/website/view_serverping.php on line 127

**Comment by AMGitsKriss** [comment]
Ah! It you're using a MinecraftPing object instead of a MinecraftQuery object. 
In that case, the following should get you a player count.
`<?php echo $Ping->Query()['players']['online']; ?>`

In case you don't know: You can use `print_r($someArray);` on an array to see it's structure. Then viewing the page source will show you a more readable structure.

**Comment by ryancito02** [comment]
I guess that was a wrong on my end by not informing you about Ping. However, my new code is..
       <div class="container">
        <div class="jumbotron">
                        <h1>Minecraft Ping PHP Class</h1>

 <?php echo $Ping->Query()['players']['online']; ?> 

*So you can see where I placed it*

But when trying to load the webpage, mydomain.com/view_serverping.php,
it says,

Minecraft Ping PHP Class

Notice: Undefined variable: Ping in /home/alarm/website/view_serverping.php on line 84

Fatal error: Uncaught Error: Call to a member function Query() on null in /home/alarm/website/view_serverping.php:84 Stack trace: #0 {main} thrown in /home/alarm/website/view_serverping.php on line 84

Should I try placing the PHP echo further down in the webpage?

Does it need to display the neat table you made first?

Thanks!

**Comment by AMGitsKriss** [comment]
Assuming you're using the example view_serverping.php:

Just replace $Ping with $Query. 

That's my bad, I copy pasted it straight from my own page.

**Comment by ryancito02** [comment]
I hate to come back again, but this time it still didn't work.

Warning: fwrite() expects parameter 1 to be resource, null given in /home/alarm/website/src/MinecraftPing.php on line 86

Warning: fwrite() expects parameter 1 to be resource, null given in /home/alarm/website/src/MinecraftPing.php on line 87

And the code is..

<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8">
        <title>Minecraft Ping PHP Class</title>

        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
        <style type="text/css">
                .jumbotron {
                        margin-top: 30px;
                        border-radius: 0;
                }

                .table thead th {
                        background-color: #428BCA;
                        border-color: #428BCA !important;
                        color: #FFF;
                }
        </style>
</head>

<body>
    <div class="container">
        <div class="jumbotron">
                        <h1>Minecraft Ping PHP Class</h1>


        <?php echo $Query->Query()['players']['online']; ?>



                        <p>This class was created to query Minecraft servers. It works starting from Minecraft 1.0.</p>

**Comment by AMGitsKriss** [comment]
Did the page show you server info when you first downloaded it? To me, that sounds like a connection issue.

**Comment by ryancito02** [comment]
Yes, I even logged on the Server and it said 1 Online down in your Table Array, but up there under 
the title it still said the Warning about FWrite

**Comment by AMGitsKriss** [comment]
If you scroll up, you'll see that the query object is destroyed/closed. Move the if statement.

**Comment by ryancito02** [comment]
Well, I moved the if Query = null function down past the php echo the players, and now no errors pop up. It is just a normal your page now, nothing has changed. The Player Count is not showing.
