### ISSUE TITLE
Trash hostname

### ISSUE THREAD

**Issue by webadequate** [xPaw/PHP-Minecraft-Query#123]
Hello. 
I got some issue with response **HostName**:

> ?8?m-]?5?m--?2?l ?b?l+!6?c?l7/2,$ ?5?m--?8?m[-?c  ?f?lKavBuy.Ru  ?e?l1.8-1.10                ?b?l?e?lSurvival?b?l?b,?a?lMarry?b?l?b,?b?lSkyWars,?c?lClans?b?l?b,?f?lParkour

How to convert it into human view?

**Comment by xPaw** [comment]
Something like this: https://github.com/Spirit55555/PHP-Minecraft#minecraftcolorsphp
