### ISSUE TITLE
MinecraftQuery doesn't work with domain

### ISSUE THREAD

**Issue by WyRe** [xPaw/PHP-Minecraft-Query#127]
I've hosted in my own machine a Minecraft server and my personal website, I'm trying to use this [wordpress plugin](https://github.com/MCServerStatus/MCServerStatus-WordPressWidget) which uses your library to make queries, I've got of course enabled query port in server.properties and opened in my router, in fact I can get that plugin working when I use my host IP.

The issue is that when I use my purchased and pointed to my IP domain the plugin doesn't work and I get an offline state. What do you think about that? 

Thank you so much.

**Comment by Spirit55555** [comment]
What is the IP, port and domain name?

Send a PM, if you don't want the info to be public.

**Comment by Khalphion** [comment]
When did you assign your IP to that domain? You should know that DNS Servers need several hours to days to update. Probably waiting some time is the solution.

**Comment by WyRe** [comment]
@Khalphion approx more than 48 hours.

@Spirit55555 [lentium](https://lentium.xyz) I've not privacy in my domain, anyone can do a whois. 213.254.78.95

**Comment by Spirit55555** [comment]
https://mcsrvstat.us/server/213.254.78.95

I suspect that your webserver does not support PHP sockets.

**Comment by WyRe** [comment]
I get available (online) status in your link, don't if I use my domain but with IP does. My webserver is Apache and is using php 7.1.2

I don't think my issue is related with php or webserver because with IP works and doesn't with domain. This issue has start when my ISP have changed my IP due variation in my agreement, with old IP does work perfectly with both, IP and domain. 

Anyway I could enable sockets extension in php.ini by uncomment 

;extension=sockets.so 

I've tried that and restarted apache server but doesn't work either.

**Comment by WyRe** [comment]
paradoxically now I'm getting available status from 

https://mcsrvstat.us/server/lentium.xyz

**Comment by WyRe** [comment]
As you can see if I use my public IP in the widget setup does work properly

https://lentium.xyz/

**Comment by WyRe** [comment]
It was my /etc/hosts setup guys, 

Thank you anyway and sorry for the inconveniences.
