### ISSUE TITLE
Some PE servers answers "Failed to receive challenge."

### ISSUE THREAD

**Issue by pavel-grom** [xPaw/PHP-Minecraft-Query#129]
Some PE servers answers "Failed to receive challenge."
Those servers is online, for example https://minecraftpocket-servers.com/server/5213/

**Comment by jasonwynn10** [comment]
sounds like that server has query off

**Comment by pavel-grom** [comment]
No, that server query on.
I wrote this class https://github.com/pavel-grom/php-minecraft-pe-query.
Maybe you can embed this class in your repository.
It can query PE servers that your repository can't.
P.S. I tried to use docs for mpce http://wiki.vg/Pocket_Minecraft_Protocol,
but I could not understand it.
I found a way in somehow pyton lib.
Sorry my perfect english.

**Comment by xPaw** [comment]
I implemented this in https://github.com/xPaw/PHP-Minecraft-Query/commit/881072933d4537f334ce96ebcf687868c100fbb9 and released v3.
