### ISSUE TITLE
Reserved Character Handling

### ISSUE THREAD

**Issue by jrdiver** [xPaw/PHP-Minecraft-Query#131]
A few mods (like <CoFH ASM>) break the code due to the mod name having "<>" around it and HTML tries to process this as a HTML tag.

I may be missing something but im not seeing an easy way to slip a line of code in to "clean" or "escape" these characters.  This is happening when pinging a forge modded server on 1.10.2, specifically Jrdiver's Modpack.

As a workaround, i set up a couple lines of php to check the returned code for these characters and remove them, but there is probably a better place to put this.

As a sidenote, Query writes it off as a vanilla server, while ping returns the list of mods.

**Comment by xPaw** [comment]
This is not an issue with the library. You want to use `htmlspecialchars` on all the strings that are displayed.
