### ISSUE TITLE
I have this problem

### ISSUE THREAD

**Issue by fernandopal** [xPaw/PHP-Minecraft-Query#132]
Screenshot: http://subefotos.com/ver/?240ef5b428779425881d8296b1fb2627o.png
Web: estado.minebone.com

What i can do?

**Comment by Spirit55555** [comment]
What is the problem?

**Comment by fernandopal** [comment]
In the page they appear "arrays {" and that which is not formatted and looks horrible

**Comment by Spirit55555** [comment]
That is the JSON Chat format, look at this if you need to convert it: https://github.com/Spirit55555/PHP-Minecraft#minecraftjsoncolorsphp

**Comment by Spirit55555** [comment]
And if you mean the general way the page looks, that is because it shows it with print_r(), you have to integrate the library in your code.

**Comment by fernandopal** [comment]
I do not understand how I can use that in my page, what I want is that the text does not appear so 
Array
(
    [name] => BungeeCord 1.8.x-1.12.x
    [protocol] => 335
)
if not something like this:
BungeeCord 1.8.x-1.12.x

**Comment by Spirit55555** [comment]
You have to learn PHP in order to use it.
