### ISSUE TITLE
No work. Operation not permitted

### ISSUE THREAD

**Issue by Andrey228322** [xPaw/PHP-Minecraft-Query#137]
Hi, i have problem with script.
Notice: fwrite(): send of 7 bytes failed with errno=1 Operation not permitted in
I contact to support website. and he say:
Need tell him info:
1. locale account
2. external IP address
3. port
4. protocol (TCP/UDP)
5. direction (In, Out, Both)

Can you say what need tell him?

**Comment by xPaw** [comment]
https://stackoverflow.com/a/12153349/2200891

Not an issue with this library.
