### ISSUE TITLE
Support for the official Bedrock server

### ISSUE THREAD

**Issue by exwizzard** [xPaw/PHP-Minecraft-Query#141]
The official server was released today and is currently in alpha testing:

https://minecraft.net/en-us/download/server/bedrock/

The Query library fails to work at the moment and I believe its because the server is using UDP.

**Comment by NurdTurd** [comment]
> The Query library fails to work at the moment and I believe its because the server is using UDP.

It's not failing due to it being UDP. In fact, Minecraft Java Edition is UDP based.

It's failing as it's a different protocol. So, someone would need to make a PR with the required changes.

**Comment by NurdTurd** [comment]
> The Query library fails to work at the moment and I believe its because the server is using UDP.

It's not failing due to it being UDP. In fact, Minecraft Java Edition is UDP based.

It's failing as it's a different protocol. So, someone would need to make a PR with the required changes.

**Comment by xPaw** [comment]
I implemented this in https://github.com/xPaw/PHP-Minecraft-Query/commit/881072933d4537f334ce96ebcf687868c100fbb9 and released v3.
