### ISSUE TITLE
Update ping for 1.15 protocol

### ISSUE THREAD

**Issue by GershonR** [xPaw/PHP-Minecraft-Query#148]
Hello, i'm using this library as a dependency and I noticed that for servers that are on 1.15.1 you get a 'Server returned too few data' exception. Servers that are 1.14.4 and lower seem to be working fine, so I believe there was some change in the protocol that caused some breakage.

https://github.com/xPaw/PHP-Minecraft-Query/blob/497af1df031e1fecfa1734727286a876558d9380/src/MinecraftPing.php#L120

**Comment by xPaw** [comment]
Can you use `MinecraftQuery`?

**Comment by GershonR** [comment]
Unfortunately no, i'm using forum software that uses this as a dependency. I was able to find a small work around by replacing the exception with an external api call and parsing the json.

**Comment by xPaw** [comment]
But does it work? Query should be preferred as it's actually meant for query purposes.

**Comment by GershonR** [comment]
I'm not using it for query purposes, the forum software uses it to display only basic information that comes from ping. The ping protocol gives you back the same data as you would see from a ping on the server screen which is just MOTD, players, icon and version. 

The forum software that i'm using really only needs to know the player count so all the data from query would be unnecessary. So in my case I need to use the ping class rather than query class.

**Comment by jensz12** [comment]
![image](https://user-images.githubusercontent.com/1682377/71382932-6a048200-25da-11ea-8943-c4965c5e58cc.png)

I have absoultely no issues pinging any MC servers, using this library. The examples is from https://mcsrvstat.us/server/minecraftserver.dk

**Comment by GershonR** [comment]
I did get an error using that website, it might be the same error that I was getting with 'Server returned too few data'. Perhaps it is unable to parse the favicon or MOTD and this is causing the exception to happen?

I am able to use other external API's using the ping protocol:
https://eu.mc-api.net/v3/server/ping/158.69.121.188:25684
http://mcapi.us/server/status?ip=158.69.121.188&port=25684

**Comment by xPaw** [comment]
Okay after looking, the data is on the socket, but it fails to read it as varint stuff seems to not work correctly.

**Comment by GershonR** [comment]
Works perfectly, thank you!
