### ISSUE TITLE
Getting names of players online without query or rcon

### ISSUE THREAD

**Issue by chickenputty** [xPaw/PHP-Minecraft-Query#152]
From https://github.com/xPaw/PHP-Minecraft-Query/issues/54
"That should be possible to obtain with MinecraftServerPing right?"

Isn't this possible now? I don't see the data returning in the ping method now, however, another service that uses the ping method is able to (https://api.mcsrvstat.us/).

**Comment by xPaw** [comment]
The ping protocol just receives a json object from the server, so whatever servers send you, that's what you get.

**Comment by chickenputty** [comment]
> The ping protocol just receives a json object from the server, so whatever servers send you, that's what you get.

How do I access this data with this php library?

**Comment by chickenputty** [comment]
![image](https://user-images.githubusercontent.com/1813460/77802046-0f028100-7048-11ea-8997-60cc8e94a9d6.png)
@xPaw
