### ISSUE TITLE
Doesn't work in local network

### ISSUE THREAD

**Issue by Arm1nasss** [xPaw/PHP-Minecraft-Query#153]
Hello, i am hosting a minecraft server on the same ipv4 address as a web server where this rcon code is, and i cant connect it with rcon, i so far tried using ipv4 / 127.0.0.1 / localhost / public ip addres to connect to the rcon, but it doesnt work. 

I am thinking maybe this code doesnt work if the rcon code and mc server is on the same local network?
Can someone help me?

**Comment by xPaw** [comment]
The code doesn't care if it's local or remote. It's up to you to fix your network/firewall/setup/whatever.
