### ISSUE TITLE
Is it possible to use this script with MCPE servers?

### ISSUE THREAD

**Issue by richicru** [xPaw/PHP-Minecraft-Query#94]
I'm looking for a script working with MCPE servers but I had no luck. Maybe there were any tweaks to make this code works with pocket edition servers.
Thanks

**Comment by xPaw** [comment]
As far as I'm aware, there is no official server software for MCPE from Mojang. It's up to server developers to implement same query protocols like Minecraft on PC does.

**Comment by williamtdr** [comment]
To answer your question: Yes. Pocketmine, the MCPE server, supports the UT3 protocol. Just set the port to 19132 (default) instead of 25565 (PC default). 

Source: Using it for my own MCPE network, you can see the result at status.lbsg.net
