### ISSUE TITLE
BungeeCord not being queryed. 

### ISSUE THREAD

**Issue by J0ker98** [xPaw/PHP-Minecraft-Query#95]
When I try to use this script with Bungee it tell me "Failed to get challenge"... Can this be fixed? If so, how?

Also is possibile to get at least the server status without the server allowing query on server.proprieties, and maybe online players and max players too?

**Comment by xPaw** [comment]
Have you tried using MinecraftPing?

**Comment by J0ker98** [comment]
Yes, with MinecraftPing it tells me "No informations received"... I just need a way to check if the server is online or not.

**Comment by xPaw** [comment]
Then just open a socket to ip/port and see if it responds, there's no need to use a query library for that.

**Comment by J0ker98** [comment]
Right now I use this:
<?php

$server_ip = "example.com";
$lobby_port = 25565;

$lobby = @fsockopen($server_ip, $lobby_port, $empty, $empty, 1); 

 if($lobby !== FALSE) {

echo "Online";

} else {

echo "Offline";

}
?>

The problem is that even if I query an unexisting server is always tell me that it is online
