### ISSUE TITLE
Add variables to the query

### ISSUE THREAD

**Issue by wiffos** [xPaw/PHP-Minecraft-Query#96]
Hi, can you help me I want to use this query but it seems very difficult to use, you can add variables to the query, for example:
$ stats ['hostname'], $ stats ['players'], $ stats ['maxplayers'] ...
I think that much easier to use the query!

**Comment by xPaw** [comment]
`GetInfo()` already returns an array with data.

**Comment by wiffos** [comment]
Yes but I need to separate content, the array shows me all together!

**Comment by xPaw** [comment]
If you don't know how to work with arrays, please don't create issues.

**Comment by wiffos** [comment]
yes but i get this error:
Failed to receive challenge.
#0 /Applications/MAMP/htdocs/server/view.php(24): xPaw\MinecraftQuery->Connect('mc.hypixel.net', 25565, 1)
#1 {main}

**Comment by Spirit55555** [comment]
mc.hypixel.net does not support Query, you have to use ServerPing.
