### ISSUE TITLE
Can't query many servers

### ISSUE THREAD

**Issue by user23145** [xPaw/PHP-Minecraft-Query#97]
When I query some of the biggest servers out there, they all show up as "offline", when they're not.

Here are some of the servers I'm talking about:

* mineverse.com
* play.gotpvp.com
* mc.desiredcraft.net
* pvp.originmc.org

Anyone else have issues querying these servers? Why?

**Comment by xPaw** [comment]
Are you using `MinecraftPing`?

**Comment by Spirit55555** [comment]
None of the listed servers have Query enabled, so you have to use ServerPing.

**Comment by user23145** [comment]
How are some Minecraft server lists, like the one below, able to still query for player count when I can't query their server?

http://minecraftservers.org/server/58086

**Comment by xPaw** [comment]
Use `ping`, not `query` to get info from these servers.
