### ISSUE TITLE
Multiple Connect issue

### ISSUE THREAD

**Issue by Tetdoss** [xPaw/PHP-Minecraft-Query#98]
Hello, i'm using Bungee with several servers and I want to display online players with only one instance of MinecraftQuery.
The issue is that if a server has 0 player, it will display the players of the previous server handle with Connect function.

To solve this, add in MinecraftQuery.php a else case :

if( $Players )
{
  $this->Players = Explode( "\x00", $Players );
}
else // add this else case
  $this->Players = array();

I want you to edit this because i'm using Composer ;)

Thank you

**Comment by xPaw** [comment]
Bungee doesn't send `player_` bit if there are no players? Just wondering if you see any PHP warnings related to accessing unset array keys.

**Comment by Tetdoss** [comment]
I'm not calling Connect on the bungee server, i'm using Connect just on different servers running in localhost. There is no warning and the array isn't reset if there are no players online.

Thanks for the fix ;)
